language: cpp
compiler:
  - g++

env:

  global:
    # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "PCMie0mk8pknLR0rS6Y6VGSnvJOJsKH13/lmlrU0o+45f4PCmGJL60N/3j7ufAr+5qRDRsJdGhz5Hgo1RkRLDCzctcidygrTLHOHVhMeRqmaVAXguRquK4BP4Vp4hTsNJSfWGIIc86RabtnqfYS18OwdAbj12v9sx1nNz7Y179I="

addons:
  coverity_scan:
     project:
       name: "masc-ucsc/esesc"
     description: "ESESC: A Fast Multicore Simulator"
     notification_email: southerngs@gmail.com
     build_command_prepend: "sudo apt-get install libboost-dev bison flex libglib2.0-dev libncurses5-dev; cd ..; cmake -DCMAKE_BUILD_TYPE=Debug esesc"
     build_command: "make"
     branch_pattern: coverity_scan

script:
  - echo "Done"


