language: cpp
compiler:
  - gcc
  - clang

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

before_install:
  - sudo apt-get install libboost-dev                                                                                                                                                    
  - sudo apt-get install bison flex                                                                                                                                                      
  - sudo apt-get install libglib2.0-dev                                                                                                                                                  
  - sudo apt-get install libncurses5-dev  

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../esesc -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script: make

after_script:
  mkdir run
  cd run
  cp ../../esesc/conf/* .
  cp ../../esesc/bins/* .
  ../main/esesc

